### ISSUE TITLE
Unnecessary escape character near end of page 

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/kubernetes-service#106]
Page: [NetApp HCI Requirements](https://docs.netapp.com/us-en/kubernetes-service/hci-requirements.html)

There's an extra visible escape character at the very end

![image](https://user-images.githubusercontent.com/16622642/61677967-02e55780-ad34-11e9-9386-1bd8e7d260aa.png)

**Comment by ebarcott** [comment]
Thank you! Fixed.
