### ISSUE TITLE
Networking field descriptions in HCI cloud services wizard need to be updated

### ISSUE THREAD

**Issue by amgrissino** [NetAppDocs/kubernetes-service#132]
Page: [Enable NKS for Your NetApp HCI Account](https://docs.netapp.com/us-en/kubernetes-service/hci-enable-nks-for-netapp-hci.html)

In the "Select Networking options" section, change this: 
•	NetApp Kubernetes Service Management Network: Enter IP addresses and information needed for service and workload clusters for the NetApp Kubernetes Service.
•	NetApp Kubernetes Service Workload Network: Enter network information needed to support your workload clusters, on which you place your applications. When you create your workload clusters, NetApp Kubernetes Service uses the IP addresses entered here.
•	NetApp Kubernetes Service Data Network: Enter network information needed to connect your Kubernetes workload clusters to persistent volume claims (PVCs) on your NetApp HCI system.

to this: 
•	NetApp Kubernetes Service Management Network: Select the vSphere distributed port group to use for management traffic for the NKS service cluster. This network requires outbound Internet access. 
•	NetApp Kubernetes Service Workload Network: Select the vSphere distributed port group to use for management traffic for the NKS user (workload) clusters. This network requires outbound Internet access.
•	NetApp Kubernetes Service Data Network: Select the vSphere distributed port group to use for persistent volume data traffic for the NKS user clusters. This is a private, non-routed network.

Thank you! 
AM

**Comment by ebarcott** [comment]
Updated and pushed to production, thank you!
