### ISSUE TITLE
Double link in docs page

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/kubernetes-service#149]
Page: [Create a Kubernetes Cluster on NetApp HCI](https://docs.netapp.com/us-en/kubernetes-service/create-netapp-hci-cluster.html)

This page is linked twice in the TOC, which looks sort of broken. It should exist only once in the TOC but could have multiple references linking to it!

**Comment by ebarcott** [comment]
Thanks, Phoebe! Fixed.
