### ISSUE TITLE
Explain "2x4" and NKS on non-HCI hardware 

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/kubernetes-service#159]
Page: [NetApp HCI Requirements](https://docs.netapp.com/us-en/kubernetes-service/netapp-hci-requirements.html)

- Expressions like "2x4" should be explained. Not everyone owns a NetApp HCI cluster or understands what these expressions mean and which is storage and which compute 
- "We do not currently support cloud services on non-HCI systems" - that's actually no longer true (and it also doesn't apply to HCI, it was a policy about "on-prem NKS" until FlexPod and generic VMWare solutions were launched)

**Comment by ebarcott** [comment]
Thanks scaleoutsean! Both items have been updated in the requirements doc.
