### ISSUE TITLE
Incorrect URL In Notification Example

### ISSUE THREAD

**Issue by sgryczan** [NetAppDocs/kubernetes-service#170]
Page: [Notifications](https://docs.netapp.com/us-en/kubernetes-service/api-notifications.html)

In the first example on the page, the URL used is:  https://api.nks.netapp.io/orgs/user/notifications

However, I believe it should be:  https://api.nks.netapp.io/user/notifications. The above address returns an error.

**Comment by ebarcott** [comment]
Good catch, thank you! Fixed.
