### ISSUE TITLE
Need a bit more detail on the meaning of "eligible for upgrade"

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/kubernetes-service#211]
Page: [Upgrade Kubernetes on an NKS Cluster](https://docs.netapp.com/us-en/kubernetes-service/upgrade-kubernetes-on-an-nks-cluster.html)

"If your cluster is not eligible for a one-click upgrade, you will need to perform the upgrade by hand."

How is this eligibility determined? Is it a combination of technical factors (such as cluster upgrade routines), cluster environment (where it runs) and K8s requirements?

**Comment by ebarcott** [comment]
Upgrade eligibility is determined by a combination of factors you reference, and will vary based on the upgrade specifics (which version to which version). Thus, we have opted to keep the language in the documentation vague since it isn't feasible to list all specifics.
