### ISSUE TITLE
Incomplete list of outgoing destinations for NKS on NetApp HCI

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/kubernetes-service#233]
Page: [Network Security and Access Controls](https://docs.netapp.com/us-en/kubernetes-service/whitelist-ports-and-ip-addresses.html) does not list these outgoing destinations:

* https://bintray.com (undocumented redirect from repo.netapp.com)
* https://cloud.netapp.com (undocumented)

Can we document all outgoing destinations and IPs including redirects and keep them up to date?

**Comment by hulquest** [comment]
@scaleoutsean When deploying NKS or CV on HCI, both of those URLs are accessed.  

- https://repo.netapp.com redirects to https://bintray.com/netapp-downloads.  This is an outbound connection to NetApp package repositories.
- https://cloud.netapp.com is an outbound connection that is verified at the moment and reserved for future use.

**Comment by scaleoutsean** [comment]
Thank you @hulquest. I will assume with the PR the list is now complete.

**Comment by hulquest** [comment]
Correct and we know where to go when something changes.

**Comment by scaleoutsean** [comment]
@hulquest it seems the list is not complete.
```
08:13:17 Running command [ docker run -d -v /registration:/registration -p 80:8080 gcr.io/nks-images/nks-bootstrap-agent:0.3.0-86b41a3 ]
Unable to find image 'gcr.io/nks-images/nks-bootstrap-agent:0.3.0-86b41a3' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
```

**Comment by hulquest** [comment]
@scaleoutsean you're right, I missed that one.  I _believe_ that is the only omission.  I'll add Skeggi to this org/repo or start a slack conversation to confirm the NKS dependencies.

**Comment by skeggi** [comment]
@hulquest I also believe that is the last one, be we will do a further review/verification.

**Comment by skeggi** [comment]
The current dev version of NKS is pulling helm3 from this location:
https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz

**Comment by ebarcott** [comment]
Hi guys! Sounds like we need to add https://get.helm.sh to https://docs.netapp.com/us-en/kubernetes-service/whitelist-ports-and-ip-addresses.html - if someone can fill in the other blanks for me (port, direction, purpose, and description) I can update the document.

**Comment by scaleoutsean** [comment]
@skeggi is helm.sh yet another addition for the current release of HCC or a future release? 
I don't know who's supposed to help Erika finalize this, is it @hulquest or you?

**Comment by hulquest** [comment]
As it stands at this moment, prod does not pull helm3.  The next release (next month) will.  Do we coordinate the release of the docs with the product?  Or should we proactively update the doc?

**Comment by ebarcott** [comment]
It's probably best to coordinate with the release. If you can send me the info, I will publish the updated doc on the next release date (Feb 11, I believe?)

**Comment by arnarpall** [comment]
We are pulling the prometheus docker image from the docker registry.

docker.io

**Comment by ebarcott** [comment]
Per offline discussion, I collapsed all of the outbound 443 entries into one table row.

**Comment by scaleoutsean** [comment]
@ebarcott does that mean that all references to spencific endpoints have been removed? 
I see "Varies based on the details of your installation" in a recent commit.

This means any site that requires whitelisting for outgoing will ask for a list. Originally I created the issues because 2-3 were missing. With this commit all destinations that need to be whitelisted to provide to "network team" are missing.

Is the list of outgoing destinations going to appear in some other page or is that it?

**Comment by ebarcott** [comment]
Yes, references have been removed. Feedback from the engineering department is that it would create too much overhead to constantly maintain and update the list. Also, it's not considered realistic to document all possible endpoints, as this will vary based on what customers opt to install on their clusters. 

Instead, we opt to recommend a blanket policy of opening outbound access on port 443. If that won't work for a specific customer, they can discuss their needs with their account manager and we can try to put together a list for them.
