### ISSUE TITLE
Adding dates to Whats New page?

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/kubernetes-service#240]
Page: [What’s New](https://docs.netapp.com/us-en/kubernetes-service/news.html)

Would it be possible to add dates to anything added to the Whats New page so I can keep a track of chronological updates over time? I do subscribe to the RSS feed, but it's not always clear what the latest update is or when it occurred.

**Comment by ebarcott** [comment]
Good idea, thank you! I have added dates.
