### ISSUE TITLE
SSH User for Debian Images Missing

### ISSUE THREAD

**Issue by biggedi** [NetAppDocs/kubernetes-service#253]
Page: [SSH to a Node in an NKS Cluster](https://docs.netapp.com/us-en/kubernetes-service/ssh-to-a-node-in-an-nks-cluster.html)

The docs are missing the user to SSH into Debian-based NKS clusters.

**Comment by ebarcott** [comment]
Thanks! I have updated the docs (the user name for Debian is "admin").
