### ISSUE TITLE
Dead link, hard to find VMware binaries 

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/kubernetes-service#265]
Page: [Sitemap](https://docs.netapp.com/us-en/kubernetes-service/sitemap.html)

1) Dead VMware link (https://docs.netapp.com/us-en/kubernetes-service/kubernetes-service/create-vmware-cluster.html)

2) No one can find binaries required for installation on VMware

**Comment by ebarcott** [comment]
I'm fixing the sitemap URL now, thanks for the heads up!

Re #2, we have changed the procedure for VMWare and Flexpod. Users need to get binaries from their account manager.
