### ISSUE TITLE
better instruction for accessing the dashboard...

### ISSUE THREAD

**Issue by forgosh** [NetAppDocs/kubernetes-service#310]
Page: [NKS End Of Life (EOL)](https://docs.netapp.com/us-en/kubernetes-service/eol.html)

This is a better command for getting the token:
     [10:52 AM] Forgosh, Seth
This is a better command to get the token:

kubectl -n kube-system describe $(kubectl -n kube-system get secret -n kube-system -o name | grep namespace) | grep token

To avoid having to proxy the dashboard every time you want to use it, you can edit the dashboard service to switch from a ClusterIP to a NodePort. Thus webpage (https://www.thegeekdiary.com/how-to-access-kubernetes-dashboard-externally/) shows you how but you do need to change kube-system to kubernetes-dashboard in the commands. You might also have to edit the dashboard-metrics-scraper service. If you do, set the nodePort to 32415.

**Comment by ebarcott** [comment]
Updated with your changes, thank you!
