### ISSUE TITLE
Policy listet does not reflect permissions for deploying EKS cluster 

### ISSUE THREAD

**Issue by Mundy667** [NetAppDocs/kubernetes-service#32]
Page: [Create Credentials on Amazon Web Services (AWS)](https://docs.netapp.com/us-en/kubernetes-service/create-auth-credentials-on-aws.html)

Please check the Policy in the docs. There are permissions missing for deploying AKS cluster. Eg. Cloudformation:CreateStack etc.... 

All EKS deployments with this policy will fail due to unsufficient rights.

**Comment by ebarcott** [comment]
Thanks for letting us know! We are in the process of reworking the documentation. The new version will be published within the next week.
