### ISSUE TITLE
Update 'Create Credentials on Google Container Engine (GKE)' documentation

### ISSUE THREAD

**Issue by Chanda2019** [NetAppDocs/kubernetes-service#56]
It appears Google Container Engine API is now listed in the GCP API Library as Kubernetes Engine API.
![Google Container Engine (GKE)](https://user-images.githubusercontent.com/50904058/58156082-ede83b80-7c92-11e9-86f3-4b18bb067e05.jpg)

You may wish to consider updating the Cloud Docs:
[https://docs.netapp.com/us-en/kubernetes-service/create-auth-credentials-on-gke.html#enable-the-google-container-engine-api ](url)

**Comment by ebarcott** [comment]
Thanks for the heads up! We are in the process of reworking the documentation anyway, I will be sure to check it for this.
