### ISSUE TITLE
Update Azure Auth Creds procedure for the current Azure UI

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/kubernetes-service#82]
Page: [Azure Credentials](https://docs.netapp.com/us-en/kubernetes-service/create-auth-credentials-on-azure.html)

Few steps, such as Step 6: Get the Application ID (Client ID) for example seem to refer to the previous version of Azure UI which has been replaced by a newer version.

![image](https://user-images.githubusercontent.com/16622642/60766932-de0da500-a0e2-11e9-96a4-c6dff1462312.png)

**Comment by ebarcott** [comment]
Updated article and heavily revised it to clarify the process.
